# Generated by Django 4.0.6 on 2022-08-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingridients',
            name='ingridients',
        ),
        migrations.RemoveField(
            model_name='recipeingridients',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipeingridients',
            name='ingridient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='has_ingridients', to='recipes.recipe', verbose_name='ингридиенты'),
        ),
        migrations.AddField(
            model_name='recipeingridients',
            name='recipe_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_recipes', to='recipes.ingridient', verbose_name='используется в рецептах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(related_name='ingridients_in_recipe', through='recipes.RecipeIngridients', to='recipes.ingridient', verbose_name='ингридиенты'),
        ),
    ]
