# Generated by Django 4.0.6 on 2022-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipeingridients_ingridients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngridients', to='recipes.ingridient', verbose_name='ингридиенты'),
        ),
    ]
