# Generated by Django 4.0.6 on 2022-08-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingridients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingridients',
            name='ingridient_id',
        ),
        migrations.RemoveField(
            model_name='recipeingridients',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipeingridients',
            name='ingridient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='ингридиенты'),
        ),
        migrations.AddField(
            model_name='recipeingridients',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingridient', verbose_name='используется в рецептах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(related_name='in_recipes', through='recipes.RecipeIngridients', to='recipes.ingridient', verbose_name='ингридиенты'),
        ),
    ]
