# Generated by Django 4.0.6 on 2022-08-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_ingridients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridients',
            name='ingridient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingridient', verbose_name='используется в рецептах'),
        ),
    ]
