# Generated by Django 4.0.6 on 2022-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingridients_ingridient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(through='recipes.RecipeIngridients', to='recipes.ingridient', verbose_name='ингридиенты'),
        ),
    ]
