# Generated by Django 4.0.6 on 2022-08-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipeingridients_ingridient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridients',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='ингридиенты'),
        ),
    ]
