# Generated by Django 4.0.6 on 2022-08-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipeingridients_ingridient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridients',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_recipes', to='recipes.ingridient', verbose_name='используется в рецептах'),
        ),
    ]
