# Generated by Django 4.0.6 on 2022-08-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipeingridients_ingridient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridient',
            options={'ordering': ['name'], 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
