# Generated by Django 4.0.6 on 2022-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_ingridient_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-08-06 10:10', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
