# Generated by Django 4.0.6 on 2022-08-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipeingridients_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AlterField(
            model_name='recipeingridients',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingridient', verbose_name='используется в рецептах'),
        ),
        migrations.AlterField(
            model_name='recipeingridients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridients', to='recipes.recipe', verbose_name='ингридиенты'),
        ),
    ]
