version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  # исходный код
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../frontend/:/app/result_build/

  frontend:
    image: dmitriykonovalov/infra_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  web:
    image: dmitriykonovalov/infra_backend:latest
    restart: always
    volumes:
      - backend_static:/app/backend_static/
      - backend_media:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
      - frontend

volumes:
  static_value:
  media_value:
  backend_static:
  backend_media:
  postgres_data:
