# Generated by Django 4.1 on 2022-08-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_remove_recipeingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='recipes_fav_user_id_b3978f_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipeingredient',
            name='recipes_rec_recipe__35afb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='shoppingcart',
            name='recipes_sho_user_id_212d34_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscribe',
            name='recipes_sub_user_id_45db4a_idx',
        ),
    ]
